---
- name : This playbook will install apache
  hosts: all
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: latest
    - name: Start Apache
      service:
        name: httpd
        state: started 
  handlers:
    - name: Restart Apache
      service:
        name: httpd
        state: restarted   