pipeline {
    agent any

    stages {
        stage('Code Checkout') {
            steps {
                // Get some code from a GitHub repository
                git url: 'https://github.com/pratham1951/SpringMVC-calculator.git', branch: 'git-vscode'
            }

        }
         stage('Build') {
            steps {
                // Run Maven on a Unix agent.
                // sh "mvn -Dmaven.test.failure.ignore=true clean package"
                echo 'Building..'

            }

        }
         stage('Test') {
            steps {
                // Run Maven on a Unix agent.
                // sh "mvn -Dmaven.test.failure.ignore=true test"

                echo 'testing..'
            }
             post {
                // If Maven was able to run the tests, even if some of the test
                // failed, record the test results and archive the jar file.
                success {
                    junit '**/target/surefire-reports/TEST-*.xml'
                    archiveArtifacts 'target/*.jar'
                }
            }

        }
    }
}

